### ISSUE TITLE
no password or notify timeout

### ISSUE THREAD

**Issue by lisabbasil** [rtfb/i3lock#1]
Hi

It would be nice to have the option that the user does not need to enter a password to unlock the screen again, or - even better - if the user could specify a notify timeout, during which the user would not need to enter a password.

For example, the i3lock should fire up after 10 minutes of inactivity, if the user shows activity within e.g. 2 minutes after the i3lock was started, the screen unlocks without entering a password. This can be a lifesaver when giving presentations.

Is a feature like that foreseen?

Thanks.

**Comment by rtfb** [comment]
This repo is not the main place to track i3lock issues, this is only my personal clone that I used when I was fixing some bugs. The right place for all i3wm issues seems to be here: https://github.com/i3/i3/issues.
